// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrgtNBSexSwIGj9cTSj_tG9kWV9GYTrAY',
    appId: '1:438377710163:web:e0e0c1c63b3761d25ebca6',
    messagingSenderId: '438377710163',
    projectId: 'intern-d5815',
    authDomain: 'intern-d5815.firebaseapp.com',
    storageBucket: 'intern-d5815.appspot.com',
    measurementId: 'G-H1WMG5E2E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8M2L6VazBWuayTZtB0AmjGGtnH7AdebE',
    appId: '1:438377710163:android:d3b318647b79b2d65ebca6',
    messagingSenderId: '438377710163',
    projectId: 'intern-d5815',
    storageBucket: 'intern-d5815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyq6alV8VDwWCo4D21ase3rZwTFiwNFu0',
    appId: '1:438377710163:ios:c0be01fa7797e9555ebca6',
    messagingSenderId: '438377710163',
    projectId: 'intern-d5815',
    storageBucket: 'intern-d5815.appspot.com',
    iosBundleId: 'com.example.intern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyq6alV8VDwWCo4D21ase3rZwTFiwNFu0',
    appId: '1:438377710163:ios:c0be01fa7797e9555ebca6',
    messagingSenderId: '438377710163',
    projectId: 'intern-d5815',
    storageBucket: 'intern-d5815.appspot.com',
    iosBundleId: 'com.example.intern',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrgtNBSexSwIGj9cTSj_tG9kWV9GYTrAY',
    appId: '1:438377710163:web:232a7eea06f7624a5ebca6',
    messagingSenderId: '438377710163',
    projectId: 'intern-d5815',
    authDomain: 'intern-d5815.firebaseapp.com',
    storageBucket: 'intern-d5815.appspot.com',
    measurementId: 'G-S6W6V37MPS',
  );
}
